### ISSUE TITLE
4.5.1 with Typescript crash (vhs-utils)

### ISSUE THREAD

**Issue by Tawagot0** [videojs/m3u8-parser#119]
Hello, my project crash with m3u8-parser (4.5.1) and MR  #118 @brandonocasey 

Environment: Linux
Tested on Windows and working but not on Linux, and working with downgrade to 4.5.0 with Linux.

```
/root/project/node_modules/@videojs/vhs-utils/es/stream.js:121
export { Stream as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/root/project/node_modules/m3u8-parser/dist/m3u8-parser.cjs.js:9:30)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/root/project/src/m3u8.ts:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
```

**Comment by clementallen** [comment]
I get the same, this can be replicated in Runkit by just importing the module.

`4.5.1` broken: https://runkit.com/embed/hj5aa8uahdju

`4.5.0` working: https://runkit.com/embed/vja7jq5zw7n3

**Comment by gkatsev** [comment]
Thanks for opening the issue, we'll take a look.

**Comment by gkatsev** [comment]
We fixed in in #120. Next patch release should be out soon.

**Comment by brandonocasey** [comment]
Should be out as a part of 4.5.2

**Comment by clementallen** [comment]
Thanks for the quick response @gkatsev @brandonocasey - tested the new version and it's working for me 👍

**Comment by gkatsev** [comment]
Thanks for verifying @clementallen!
