### ISSUE TITLE
Exception on #EXT-X-MEDIA-TIME tag

### ISSUE THREAD

**Issue by ost12666** [videojs/m3u8-parser#22]
We have a vtt playlist with non standard #EXT-X-MEDIA-TIME tag:

#EXT-X-MEDIA-TIME:0.0

The parser then tries to parse the attributes from "-TIME:0.0" probably because it somehow detects this as the #EXT-X-MEDIA tag.

This causes this exception here:  ` attr = /([^=]*)=(.*)/.exec(attrs[i]).slice(1);`

> Exception has occurred: TypeError
> TypeError: Cannot read property 'slice' of null
>     at parseAttributes (/Users/ost/Development/adaptive_playground/Server/node_modules/m3u8-parser/es5/parse-stream.js:60:41)
>     at ParseStream.push (/Users/ost/Development/adaptive_playground/Server/node_modules/m3u8-parser/es5/parse-stream.js:339:30)
>     at LineStream.<anonymous> (/Users/ost/Development/adaptive_playground/Server/node_modules/m3u8-parser/es5/stream.js:124:21)
>     at LineStream.trigger (/Users/ost/Development/adaptive_playground/Server/node_modules/m3u8-parser/es5/stream.js:91:24)
>     at LineStream.push (/Users/ost/Development/adaptive_playground/Server/node_modules/m3u8-parser/es5/line-stream.js:59:14)
>     at Parser.push (/Users/ost/Development/adaptive_playground/Server/node_modules/m3u8-parser/es5/parser.js:370:23)

Probably because of the unneeded '?' after the ':'

      match = /^#EXT-X-MEDIA:?(.*)$/.exec(line);

**Comment by ost12666** [comment]
This still happens

**Comment by ost12666** [comment]
Can someone review and merge this simple PR? https://github.com/videojs/m3u8-parser/pull/45

Thanks!

**Comment by ost12666** [comment]
Fixed here: https://github.com/videojs/m3u8-parser/pull/50
